//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiSuite_Proxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiSuite_Proxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///  &lt;component name=&quot;TCPU&quot; version=&quot;Unknown&quot;/&gt;
        ///  &lt;default-language name=&quot;en-gb&quot;&gt;2057&lt;/default-language&gt;
        ///  &lt;cleardata-flag&gt;False&lt;/cleardata-flag&gt;
        ///  &lt;romsurvey-flag&gt;False&lt;/romsurvey-flag&gt;
        ///  &lt;notify-level&gt;40&lt;/notify-level&gt;
        ///  &lt;point-version&gt;False&lt;/point-version&gt;
        ///
        ///  &lt;language name=&quot;en-gb&quot; code=&quot;2057&quot;&gt;
        ///    &lt;features module=&quot;&quot; type=&quot;header&quot;&gt;
        ///      &lt;feature&gt;This is a new update, be happy.&lt;/feature&gt;
        ///    &lt;/features&gt;
        ///    &lt;features module=&quot;[Note]&quot;&gt;
        ///      &lt;feature&gt;Be sure you put correct ROM version in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] emptyresponse {
            get {
                object obj = ResourceManager.GetObject("emptyresponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] emui7resp {
            get {
                object obj = ResourceManager.GetObject("emui7resp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///&lt;component&gt;
        ///&lt;name&gt;TCPU&lt;/name&gt;
        ///&lt;compress&gt;0&lt;/compress&gt;
        ///&lt;/component&gt;
        ///&lt;maxStashInfo&gt;52428800&lt;/maxStashInfo&gt;
        ///&lt;vendorInfo logfile=&quot;changelog.xml&quot; name=&quot;firmkind&quot; package=&quot;firmfile&quot; precut_size=&quot;0&quot; subpath=&quot;&quot;/&gt;
        ///&lt;files&gt;
        ///&lt;file&gt;
        ///&lt;spath&gt;firmfile&lt;/spath&gt;
        ///&lt;dpath&gt;firmfile&lt;/dpath&gt;
        ///&lt;operation&gt;c&lt;/operation&gt;
        ///&lt;md5&gt;firmMD5&lt;/md5&gt;
        ///&lt;sha256&gt;firmSHA256&lt;/sha256&gt;
        ///&lt;size&gt;firmsize&lt;/size&gt;
        ///&lt;/file&gt;
        ///&lt;file&gt;
        ///&lt;spath&gt;changelog.xml&lt;/spath&gt;
        ///&lt;dpath&gt;changelog.xml&lt;/dpath&gt;
        ///&lt;operation&gt;c&lt;/operation&gt;
        ///&lt;md5&gt;8AB3DF980B01133AC7CF3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string filelist {
            get {
                return ResourceManager.GetString("filelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oldresponse {
            get {
                object obj = ResourceManager.GetObject("oldresponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] responsedata {
            get {
                object obj = ResourceManager.GetObject("responsedata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;IMEI&quot;: &quot;&quot;,
        ///&quot;deviceId&quot;: &quot;227CA9D2&quot;,
        ///&quot;updateToken&quot;: &quot;415FD779AF&quot;,
        ///&quot;vendor&quot;: &quot;&quot;,
        ///&quot;ver&quot;: &quot;1&quot;,
        ///&quot;version&quot;: [
        ///{
        ///&quot;versionId&quot;: &quot;VersionID&quot;
        ///}
        ///]
        ///}.
        /// </summary>
        internal static string romapprovedjson {
            get {
                return ResourceManager.GetString("romapprovedjson", resourceCulture);
            }
        }
    }
}
